[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--no-optional"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = ["node_modules/.cache"]

[functions]
  included_files = ["dist/**/*"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
