[build]
  command = "npm install && ./node_modules/.bin/vite build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--no-optional"
  NODE_ENV = "production"

[functions]
  included_files = ["dist/**/*"] 