[build]
  command = "npm install && node node_modules/vite/bin/vite.js build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--no-optional"
  NODE_ENV = "production"

[functions]
  included_files = ["dist/**/*"] 